# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# NVIDIA NeMo Agent Toolkit 黑客松配置
# 支持用户自定义OpenAI兼容API

general:
  use_uvloop: true

functions:
  internet_search:
    _type: tavily_internet_search
    description: "使用Tavily API进行实时网络搜索"
  
  current_datetime:
    _type: current_datetime
    description: "获取当前日期和时间"

  job_search:
    _type: tavily_job_search
    description: "搜索求职相关信息和建议"
    
  memory_knowledge_graph:
    _type: memory_knowledge_graph
    description: "使用Memory知识图谱存储和检索信息"

llms:
  # 默认使用Bailian API (用户可修改)
  default_llm:
    _type: openai
    model_name: "qwen-plus"
    api_key: "sk-3c77827b7e9144b6b9820bc87be1e740"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - internet_search
    - current_datetime
    - job_search
    - memory_knowledge_graph
  llm_name: default_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10

